version: '2'
services:
  celery:
    build: celery/
    volumes:
     - ..:/home/kgeserver/kge-server
    depends_on:
     - redis
  web:
    build: web/
    ports:
     - "6789:8000"
    volumes:
     - ..:/home/kgeserver/kge-server
    depends_on:
     - redis
  redis:
    image: redis:alpine
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    ports:
     - "9200:9200"
    environment:
     - "http.host=0.0.0.0"
     - "transport.host=127.0.0.1"
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
