version: '2'
services:
  celery:
    build: celery/
    volumes:
     - ..:/home/kgeserver/kge-server
    depends_on:
     - redis
  web:
    build: web/
    ports:
     - "6789:8000"
    volumes:
     - ..:/home/kgeserver/kge-server
    depends_on:
     - redis
  redis:
    image: redis:alpine
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    ports:
     - "9200:9200"
    environment:
     - "http.host=0.0.0.0"
     - "transport.host=127.0.0.1"
