version: '2'
services:
  celery:
    build: celery/
    volumes:
     - ..:/home/kgeserver/work
    depends_on:
     - redis
  web:
    build: web/
    ports:
     - "6789:8000"
    volumes:
     - ..:/home/kgeserver/work
    depends_on:
     - redis
  redis:
    image: redis
